# Parameters
project: "runs/pretrainv2"
snapshot_dir: "weight"
log_dir: "log"
resume_checkpoint: "" # path to checkpoint if you want to resume training
warmup_epochs: 5
epochs: 500
save_period: 5
visual_imgs: 5
save_ckpt_freq: 50

hyp:
  min_lr: 1.0e-6
  base_lr: 1.5e-4
  weight_decay: 0.05
  gradient_accumulation_steps: 8

Model:
  name: "mae_vit_base_patch16_with_register_convstem"
  use_gan_loss: False

Dataset:
  prefix_path: "../../DATA"
  data_name: "Endoscopy"
  annotation_file: "./configs/pretrain.json"
  img_size: 224
  batch_size: 32
  num_workers: 8
  pin_memory: True
  drop_last: True
  train_json_file: "./configs/train.json"
  test_json_file: "./configs/test.json"
  meanstd_file: "./configs/meanstd.pth"
