# Parameters
project: "runs/pretrainv2"
snapshot_dir: "weight"
log_dir: "log"
resume_checkpoint: "/workspace/mae_ckpt/mae_pretrain_vit_base_full.pth" # path to checkpoint if you want to resume training
warmup_epochs: 1
epochs: 100
save_period: 5
visual_imgs: 5
save_ckpt_freq: 10

hyp:
  min_lr: 1.0e-8
  base_lr: 1.0e-4
  weight_decay: 0.05
  gradient_accumulation_steps: 1

Model:
  name: "mae_vit_base_patch16_with_register"

Dataset:
  prefix_path: "/workspace/DATA2"
  data_name: "Endoscopy"
  annotation_file: "/workspace/endoscopy/pretrain.json"
  img_size: 224
  batch_size: 256
  num_workers: 24
  pin_memory: True
  drop_last: True
  # mean: [0.485, 0.456, 0.406]
  # std: [0.229, 0.224, 0.225]
  # mean: [0.583, 0.355, 0.288]
  # std: [0.273, 0.214, 0.184]
  mean: [0.467, 0.316, 0.254]
  std: [0.291, 0.226, 0.193]
