# Parameters
project: "runs/pretrainv2"
snapshot_dir: "weight"
log_dir: "log"
resume_checkpoint: "/mnt/tuyenld/mae/pretrain/runs/pretrainv2/vit-mae-base/mae_pretrain_vit_base.pth" # path to checkpoint if you want to resume training
warmup_epochs: 2
epochs: 100
save_period: 5
visual_imgs: 5
save_ckpt_freq: 10

hyp:
  min_lr: 1.0e-6
  base_lr: 1.0e-4
  weight_decay: 0.05
  gradient_accumulation_steps: 4

Model:
  name: "mae_vit_base_patch16_with_register"

Dataset:
  prefix_path: "../../data/endoscopy"
  data_name: "Endoscopy"
  annotation_file: "/mnt/tuyenld/data/endoscopy/processed/pretrain.json"
  img_size: 224
  batch_size: 64
  num_workers: 8
  pin_memory: True
  drop_last: True
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
